# Generated by Django 4.1.3 on 2023-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
